x-airflow-common: &airflow-common
  image: safaricom-intel-airflow:latest
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__WEBSERVER__SECRET_KEY: safaricom-intel-secret
    GCP_PROJECT_ID: ${GCP_PROJECT_ID}
    GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
    GCP_CREDENTIALS_FILE: /opt/airflow/gcp/safaricom-intelligence-sa.json
    BQ_DATASET_RAW: ${BQ_DATASET_RAW}
    BQ_LOCATION: ${BQ_LOCATION}
    DBT_ACCOUNT_ID: ${DBT_ACCOUNT_ID}
    DBT_JOB_ID: ${DBT_JOB_ID}
    DBT_API_TOKEN: ${DBT_API_TOKEN}
  volumes:
    - ../dags:/opt/airflow/dags
    - ../ingestion:/opt/airflow/ingestion
    - ../logs:/opt/airflow/logs
    - ${GCP_CREDENTIALS_FILE}:/opt/airflow/gcp/safaricom-intelligence-sa.json:ro
  depends_on:
    postgres:
      condition: service_healthy
  env_file:
    - ../.env

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5

  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com"
    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    command: airflow webserver
    ports:
      - "8085:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: airflow scheduler
    restart: always

volumes:
  postgres_data: